<a href="https://colab.research.google.com/github/IrfanKarim101/Artificial-Intelligence/blob/main/normalization_and_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a dataset
data = np.array([[50, 2000],
                 [30, 3000],
                 [20, 1000],
                 [60, 4000]])

print("Original Data:")
print(data)


/bin/bash: line 1: import: command not found


NameError: name 'np' is not defined

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the data
minmax_scaled_data = scaler.fit_transform(data)

print("\nMin-Max Scaled Data:")
print(minmax_scaled_data)



Min-Max Scaled Data:
[[0.75       0.33333333]
 [0.25       0.66666667]
 [0.         0.        ]
 [1.         1.        ]]


In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Example dataset
data = np.array([[50, 2000],
                 [30, 3000],
                 [20, 1000],
                 [60, 4000]])

print("Original Data:")
print(data)

# 1. Min-Max Scaling with a specified range
scaler_minmax = MinMaxScaler(feature_range=(0, 1))  # Define the range 0-1
minmax_scaled_data = scaler_minmax.fit_transform(data)

print("\nMin-Max Scaled Data (Range 0-1):")
print(minmax_scaled_data)

# 2. Min-Max Scaling with a custom range (e.g., 5 to 10)
scaler_custom = MinMaxScaler(feature_range=(5, 10))  # Define the range 5-10
custom_scaled_data = scaler_custom.fit_transform(data)

print("\nMin-Max Scaled Data (Range 5-10):")
print(custom_scaled_data)




Original Data:
[[  50 2000]
 [  30 3000]
 [  20 1000]
 [  60 4000]]

Min-Max Scaled Data (Range 0-1):
[[0.75       0.33333333]
 [0.25       0.66666667]
 [0.         0.        ]
 [1.         1.        ]]

Min-Max Scaled Data (Range 5-10):
[[ 8.75        6.66666667]
 [ 6.25        8.33333333]
 [ 5.          5.        ]
 [10.         10.        ]]


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Example dataset
data = np.array([[50, 2000],
                 [30, 3000],
                 [20, 1000],
                 [60, 4000]])

print("Original Data:")
print(data)

# 1. Z-Score Scaling (Standardization)
scaler = StandardScaler()

# Apply Z-Score Scaling to the data
zscore_scaled_data = scaler.fit_transform(data)

# 2. Checking for zero values and modifying if necessary
# We replace zero Z-scores with a very small value (e.g., 0.0001)
zscore_scaled_data_no_zero = np.where(zscore_scaled_data == 0, 0.0001, zscore_scaled_data)

print("\nZ-Score Scaled Data (without exact zero):")
print(zscore_scaled_data_no_zero)


Original Data:
[[  50 2000]
 [  30 3000]
 [  20 1000]
 [  60 4000]]

Z-Score Scaled Data (without exact zero):
[[ 0.63245553 -0.4472136 ]
 [-0.63245553  0.4472136 ]
 [-1.26491106 -1.34164079]
 [ 1.26491106  1.34164079]]
